Repository Leafwing-Studios/leafwing_input_playback, pull requests merged in 2022-10, with the labels that each got.

#9 Add input playback
  README.md
  examples/input_capture.rs
  examples/input_playback.rs
  src/frame_counting.rs
  src/input_capture.rs
  src/input_playback.rs
  src/lib.rs
  src/timestamped_input.rs
  tests/input_capture.rs
  tests/input_playback.rs
Labels: enhancement

#14 Fix mouse movement capture
  Cargo.toml
  src/input_playback.rs
Labels: bug

#12 Serialization and deserialization of timestamped inputs
  Cargo.toml
  data/hello_world.ron
  examples/playback_serialized_input.rs
  examples/serialize_captured_input.rs
  src/frame_counting.rs
  src/input_capture.rs
  src/input_playback.rs
  src/lib.rs
  src/serde.rs
  src/timestamped_input.rs
Labels: enhancement

#21 Capture and playback `AppExit` events
  data/app_exit.ron
  examples/useless_machine.rs
  src/input_capture.rs
  src/input_playback.rs
  src/timestamped_input.rs
  tests/input_capture.rs
Labels: usability

#8 For this crate, for now, we are denying missing docs, not forbidding.
  README.md
Labels: documentation

#23 Gamepad support
  assets/fonts/FiraSans-Bold.ttf
  examples/gamepad.rs
  src/input_capture.rs
  src/input_playback.rs
  src/timestamped_input.rs
Labels: enhancement

#24 Add helpful explanation of how the crate works to the README
  README.md
Labels: documentation
